### ISSUE TITLE
Disable Gitops Feature Breaks Fleet Controller Deployment

### ISSUE THREAD

**Issue by jonathon2nd** [rancher/fleet#1166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Automated Fleet upgrade fails when upgrading Rancher to 2.7

### Expected Behavior

Things to not error out.

### Steps To Reproduce

Upgrade Rancher to 2.7
Fleet upgrade then fails

### Environment

```markdown
- Architecture: k8s
- Fleet Version: 
- Cluster:
  - Provider: Self
  - Options: 
  - Kubernetes Version: v1.24.6
```

### Logs

```markdown
helm upgrade --force-adopt=true --history-max=5 --install=true --namespace=cattle-fleet-system --reset-values=true --timeout=5m0s --values=/home/shell/helm/values-fleet-101.0.0-up0.5.0.yaml --version=101.0.0+up0.5.0 --wait=true fleet /home/shell/helm/fleet-101.0.0-up0.5.0.tgz
Error: UPGRADE FAILED: YAML parse error on fleet/templates/deployment.yaml: error converting YAML to JSON: yaml: line 27: did not find expected key
```
```


### Anything else?

I opened an issue here: https://github.com/rancher/rancher/issues/39822
But then found this repo trying to debug it, thought it might belong here better, let me know.

**Comment by kkaempf** [comment]
Which Rancher version are you upgrading from ?
Which Fleet version are you upgrading from ?

**Comment by jonathon2nd** [comment]
Upgraded from Rancher 2.6.8
Fleet looks like it is 0.3.11

**Comment by sida-khalibre** [comment]
I got the same issue after upgrading from 2.6.8 to 2.7.0

**Comment by kkaempf** [comment]
See also rancher/rancher#39822

**Comment by SharpThunder** [comment]
Hi @kkaempf
I fixed the error happening in helm chart. 
It happens because when ".Values.debug" not enabled,  securityContext added but when ".Values.gitops.enabled" parameter added after securityContext.

**Comment by onpaws** [comment]
I'm seeing the same issue, just upgraded to 2.7.0.

<img width="1671" alt="image" src="https://user-images.githubusercontent.com/182515/208815931-ad4377d0-35a7-4e83-9376-ae8fb16ffe32.png">

<img width="2048" alt="image" src="https://user-images.githubusercontent.com/182515/208814738-ad16c608-50f4-4987-a868-d39f73f165aa.png">

I'd like to try @SharpThunder 's [commit](https://github.com/rancher/fleet/commit/9dd421aa5a1236b6fe2db00921bc6abf5e103e32) (thanks!)

How can I best try it?

Should I be pointing my `local` cluster to a new `Repository` e.g.
<img width="2048" alt="image" src="https://user-images.githubusercontent.com/182515/208816958-23a0b77e-02c2-42b2-ace5-879348407834.png">

?

**Comment by SharpThunder** [comment]
I think it is not available yet, I tried to install manually however, Rancher was not stop spawning helm-operation. 
I downgraded 2.6.9 and upgrade to older version from Installed Apps.

**Comment by gmanera** [comment]
Same issue.

**Comment by pwurbs** [comment]
We are facing the same after updating Rancher from 2.6.9 to 2.6.10. Every some minute, there is a broken Hem operation with this log in the Helm container:

```
helm  upgrade --force-adopt=true --history-max=5 --install=true  --namespace=cattle-fleet-system --reset-values=true --timeout=5m0s  --values=/home/shell/helm/values-fleet-100.2.0-up0.5.1.yaml  --version=100.2.0+up0.5.1 --wait=true fleet  /home/shell/helm/fleet-100.2.0-up0.5.1.tgz
Error: UPGRADE FAILED: YAML parse error on fleet/templates/deployment.yaml: error converting YAML to JSON: yaml: line 27: did not find expected key
```

**Comment by pwurbs** [comment]
I tried it out a bit. 
In my opinion, the root cause is in this code within the deployment.yaml

```
        {{- if not .Values.gitops.enabled }}
        - --disable-gitops
        {{- end }}
```
This seems to be at the wrong place

**Comment by pwurbs** [comment]
So, the error only occurs, if gitops.enabled is set to false

**Comment by olblak** [comment]
I am renaming this issue to "Fleet upgrade failing with Rancher 2.7 & 2.6" as it also affects the 2.6 version release line

**Comment by olblak** [comment]
@pwurbs which version of fleet or rancher are you using?
The fix is available in [v0.5.2-rc.1](https://github.com/rancher/fleet/releases/tag/v0.5.2-rc.1)

**Comment by pwurbs** [comment]
@olblak I upgraded Rancher from 2.6.9 to 2.6.10

**Comment by pwurbs** [comment]
The fleet upgrade works and the error vanishes if the feature "continuous-delivery (Gitops components in fleet)" is activated in the global settings. This triggers the change of the value to true and prevents the error.
So, the issue is only relevant for users which disabled the feature in the global settings

**Comment by SharpThunder** [comment]
You are using fleet-100.2.0-up0.5.1. Fix is not merged yet to the rancher charts.

**Comment by jonathon2nd** [comment]
Still occurring in 2.7.0, not sure why it would be closed. Is it slated for a release ([pr](https://github.com/rancher/fleet/pull/1185)?)?
I would close this when it was fixed with an upgrade. I would then close this [issue](https://github.com/rancher/rancher/issues/39822) too.

**Comment by manno** [comment]
We close the issue when development has finished for the Fleet team and we consider it "done". Sadly, that is very different from fixing it in Rancher and probably month away from having it in a full release. 
We use Github issues for planning our sprints, too. We're actively discussing on how to improve the situation.


Rancher 2.7.1 was a security fix release, the next bug fix release 2.7.2 will have the new version of fleet.

**Comment by jonathon2nd** [comment]
Sure, I have the other issue that is actually tracking in Rancher. Should have thought of that.

Thanks for seeing this fixed!
