### ISSUE TITLE
Fleet falsely considers bundles in error state, when they are not

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#1386]
[SURE-5987]

#### Issue description:

We have [keda](https://keda.sh/) installed in our cluster.
We deployed a fleet that contains a helm chart of an application with, among other things, two deployments and 2 ScaledObject.
Just like the HPAs, Keda modifies the replicas , so we needed to add a diff in the `fleet.yaml` file and it works fine.

#### What finally happens :

ScaledObject objects have an “Activating” status when the trigger is pending. This is a normal status.
But Fleet considers the bundle in error status :

#### Workaround:
No

#### Actual behavior:
Fleet reporting bundle in error, when it is not.

#### Expected behavior:
Fleet should not set his bundle in error state as it is a normal state.

#### Additional notes:
This also happens with CIS Benchmarks. Fleet considers CIS scans that have completed successfully, but have a rule that is not satisfied also as being in an error state.

Also see [Rancher-users slack discussion](https://rancher-users.slack.com/archives/C013SSBKB6U/p1676994171382389)

**Comment by manno** [comment]
We need to support the state in wrangler.

**Comment by belgaied2** [comment]
> We need to support the state in wrangler.

Do you mean, we need to support every single possible state ? We need a way to consider that Custom Resources that are not in the initial list known by Fleet to be successful as soon as they are created. I think we don't have any other choice.

**Comment by dtrouillet** [comment]
As the fleet diff, would it be possible to add in fleet.yaml a field to ignore certains conditions ?

**Comment by raulcabello** [comment]
## Additionnal QA
 
### Problem
We can't control the status in Custom Resources that don't belong to Fleet or Rancher. This is causing Fleet to consider bundles in error state when they shouldn't. See what happens with keda in the issue description.
 
### Solution
Add a new field to ignore conditions. Ignore Conditions can be specified in the Bundle or in the fleet.yaml. This allows users to ignore conditions that fleet thinks are wrong, but are in an ok status.
 
### Testing

### Engineering Testing
#### Manual Testing
Steps:
- install keda
```
kubectl create namespace keda
helm install keda kedacore/keda --version 2.1.1  --namespace keda
```
- install rabbitmq (this can be changed for other if prefered)
```
helm install rabbitmq --set auth.username=user --set auth.password=PASSWORD bitnami/rabbitmq --wait
```
- create a `GitRepo` that points to a git repo that contains a `ScaledObject` resource (`ScaledObject` is a keda CR) Example: https://github.com/raulcabello/fleet-test/tree/main/keda

Then verify that:

- status should be ok if this is added to the fleet.yaml:
```
ignore:
  conditions:
   - type: Active
     status: "False"
     reason: ScalerNotActive
```

- status is in an error state because of the `ScaledObject` if the ignore conditions are removed

#### Automated Testing
[unit tests](https://github.com/rancher/fleet/blob/master/modules/agent/pkg/deployer/monitor_test.go)

**Comment by belgaied2** [comment]
@raulcabello What do you think about [ArgoCD's global solution](https://argo-cd.readthedocs.io/en/stable/operator-manual/health/) to the problem? 

I think it would be beneficial to implement some sort of custom health check for CRDs and rare scenarios for standard resources.

**Comment by markusewalker** [comment]
**QA TEST PLAN**

Scenarios
|Scenario|Test Case|
|---|---|
|1|As an admin user, install charts keda and rabbitmq, create a GitRepo and validate that the bundles come up all in an `Active` state|

**Comment by markusewalker** [comment]
Verified that this is addressed on `v2.7-head` https://github.com/rancher/rancher/commit/ed4b893709717f49c8c55cf9fe2399601007bcf8.

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version
     - Repro: `v2.7.1`
     - Validated: `v2.7-head` https://github.com/rancher/rancher/commit/ed4b893709717f49c8c55cf9fe2399601007bcf8 

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As an admin user, install charts keda and rabbitmq, create a GitRepo and validate that the bundles come up all in an `Active` state|:white_check_mark:|

**REPRO STEPS**

**Scenario 1**
1. In a client machine with my `local` cluster kubeconfig installed, ran the following commands:
```
kubectl create ns keda
helm repo add kedacore https://kedacore.github.io/charts
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm install keda kedacore/keda --version 2.1.1 --namespace keda
helm install rabbitmq --set auth.username=user --set auth.password=PASSWORD bitnami/rabbitmq --wait
```
2. Navigated back to Rancher > Continuous Delivery.
3. Created a GitRepo using `https://github.com/raulcabello/fleet-test.git`.
4. Noted that not all of the bundles are all appearing in an `Active` state; bundles appear in an error state when they should not be.

**VALIDATION STEPS**

**Scenario 1**
1. In a client machine with my `local` cluster kubeconfig installed, ran the following commands:
```
kubectl create ns keda
helm install keda kedacore/keda --version 2.1.1 --namespace keda
helm repo update
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm install rabbitmq --set auth.username=user --set auth.password=PASSWORD bitnami/rabbitmq --wait
```
2. Navigated back to Rancher > Continuous Delivery.
3. Created a GitRepo using `https://github.com/raulcabello/fleet-test.git`.
4. Validated that the bundles are all appearing in an `Active` state.
5. Viewed the logging and did note any message as originally reported.

@raulcabello I did notice the below with using your repo, though:

![image](https://user-images.githubusercontent.com/52591819/234970166-329a0550-7f7a-4597-a7c5-8b21b6ef2a97.png)

I believe it is unrelated to the validation, correct? If so, we are good to close this issue.

**Comment by raulcabello** [comment]
@markusewalker the errors you are seeing are for [cert-manager](https://github.com/raulcabello/fleet-test/tree/main/cert-manager), [chaos-mesh](https://github.com/raulcabello/fleet-test/tree/main/chaos-mesh), ... those are other apps. You probably left the path empty in the `GitRepo`, then bundle for all paths are created. Make sure you add keda in the path field in the GitRepo, and those errors should disappear.

**Comment by markusewalker** [comment]
Thanks @raulcabello, I suspected it was environmental on my end, but wanted to confirm before closing the issue. As this is unrelated to the validations done, I will go ahead and close this issue.

**Comment by eddy8700** [comment]
@kkaempf @markusewalker i am using rancher 2.7.4 and the issue is still there , any help will be appreciated on this
