### ISSUE TITLE
Poll Helm for new available versions

### ISSUE THREAD

**Issue by weyfonk** [rancher/fleet#3764]
Similarly to what GitOps supports with polling git repositories, and following semantic versioning support, Fleet should be able to poll Helm repositories in search of new versions matching a HelmOp's `version` field, whether it be:
* a version constraint, meaning that the latest available version satisfying that constraint should be installed
* an empty or wildcard (`*`) value, in which case the latest available version should be installed

Polling must be configurable using a new `pollingInterval` field, consistently with what GitOps supports.

**Comment by weyfonk** [comment]
## Additional QA
 
### Problem
When installing a Helm chart using a Fleet HelmOp resource with a wildcard or empty version field, Fleet would initially resolve the latest available version for the chart. Subsequent updates of the HelmOp would repeat this process, but the user did not have any way of ensuring that a newer chart version would be installed as soon as it would be available.

### Solution
Fleet is now able to poll a Helm repository referenced by a HelmOp , similarly to what GitOps supports for git repositories, as soon as the HelmOp meets both of the following conditions:
* its `version` field may resolve to more than one version over time, e.g. `*` (wildcard), `< 1.0.0`, `2.x.x`. Referencing a static version, such as `1.2.3`, disables polling
* its new `pollingInterval` field, which value defaults to 0, is set to a non-zero duration

### Testing
### Engineering Testing
#### Manual Testing
N/A

#### Automated Testing
##### End-to end tests
1. Creating a HelmOp, meeting the above conditions for polling, referencing a chart hosted on a test ChartMuseum instance, where version `0.1.0` of the chart is the latest version matching the version constraint
2. Checking that version `0.1.0` of the chart is installed
3. Uploading version `0.2.0` of the chart to ChartMuseum, with version `0.2.0` also matching the HelmOp's version constraint
4. Checking that version `0.2.0` of the chart is installed

##### Integration tests
* if a HelmOp bundle exists with a version constraint (instead of a static version, which should have been set by the HelmOps controller when checking Helm for the latest version matching the HelmOp's constraint), then no bundle is created
* if a polling job fails, it updates the HelmOp status' new `Polled` condition to `False`, with an error message explaining the failure

##### Unit tests
- polling job scheduling: 
    - Does not happen if one of the above conditions for polling is not met
    - Is triggered if the HelmOp's `version`, `chart`, `repo` or polling interval field changes
    - Ensures that jobs replace one another for a given key which is unique to the HelmOp
    - Deletes existing poll jobs for the given key if the HelmOp is updated such that polling no longer applies

### QA Testing Considerations
We should validate that Kubernetes events are generated, of types:
*  `GotNewChartVersion` when a new chart version is found, specifying the new version found
* `FailedToGetNewChartVersion` when a new chart version could not be found (for instance if the Helm repository is offline)

Idea: try using 2 or 3 different HelmOp resources concurrently, with different polling intervals, and check that, once a new version of the charts they reference is available, each of those charts is updated according to each HelmOp's respective polling interval?
 
#### Regressions Considerations
If no polling interval is set, a HelmOp with an empty or wildcard version (or a semantic versioning constraint) should still work as expected:
1. When the HelmOp is first created, get the latest chart version applicable to the value of the version field
2. Even if a new version of the chart is available afterwards, it should not immediately be installed if the HelmOp is not modified (as opposed to, say, if the HelmOp has a `1s` or even a `5s` polling interval)

**Comment by mmartin24** [comment]
Checked in Rancher `v2.12-6d2a9d53b44f309eac233e0f21fd9d5e806b056d-head` with  fleet `107.0.0+up0.13.0-beta.2` 

Used fleet chartmuseum from pr to perform the test with polling set to 5 seconds.
Note: had to rename chart from sleepers-chart to sleepers momentarily due to this UI issue:  https://github.com/rancher/dashboard/issues/14731

- Verified changes from one chart version to another inmidiately triggers a change
- Could NOT see event `GotNewChartVersion` being triggered

After turning the chartmuseum to 0 replicas to simulate imposiblity of getting a new version: 
- verifed an error occurred.
- verified `FailedToGetNewChartVersion` event was triggered

After returning chartmuseum to 1 replica and re-adding again the binary, the  UI still displays an error:

<img width="1882" height="902" alt="Image" src="https://github.com/user-attachments/assets/9be4ea5c-8ff4-415f-9bf8-a6fb07b4d0f0" />


Putting into review again to check those issues.

**Comment by weyfonk** [comment]
Does the error about no version being found also stay in the HelmOp's status, or is only the UI outdated, with the HelmOp having been updated as a result of polling?

The event visibility issue should be fixed by #3858.

**Comment by mmartin24** [comment]
> Does the error about no version being found also stay in the HelmOp's status, or is only the UI outdated, with the HelmOp having been updated as a result of polling?
> 
> The event visibility issue should be fixed by [#3858](https://github.com/rancher/fleet/pull/3858).

Yes, also found in status. It seems a backend issue:

When I pull the logs I can see that error as well:

```
k logs -n cattle-fleet-system helmops-5f5d69bc59-7chrq | grep "could not get a chart version" | tail -1
``` 

output:

```json
E0708 12:42:13.985102       7 event.go:359] "Server rejected event (will not retry!)" err="events \"test.18504724f5a00e88\" is forbidden: User \"system:serviceaccount:cattle-fleet-system:helmops\" cannot patch resource \"events\" in API group \"\" in the namespace \"fleet-local\"" event="&Event{ObjectMeta:{test.18504724f5a00e88  fleet-local   21832 0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []},InvolvedObject:ObjectReference{Kind:HelmOp,Namespace:fleet-local,Name:test,UID:154b78ea-d26e-447a-8fe3-9e2067875baf,APIVersion:fleet.cattle.io/v1alpha1,ResourceVersion:21974,FieldPath:,},Reason:FailedToGetNewChartVersion,Message:could not get a chart version: no chart name found,Source:EventSource{Component:fleet-helmops,Host:,},FirstTimestamp:2025-07-08 12:41:19 +0000 UTC,LastTimestamp:2025-07-08 12:42:13.983940533 +0000 UTC m=+7059.431223319,Count:12,Type:Warning,EventTime:0001-01-01 00:00:00 +0000 UTC,Series:nil,Action:,Related:nil,ReportingController:fleet-helmops,ReportingInstance:,}"
```

<img width="1878" height="931" alt="Image" src="https://github.com/user-attachments/assets/56bf8284-65b4-45c6-892b-4ea2b1b2d5b5" />
<img width="1898" height="923" alt="Image" src="https://github.com/user-attachments/assets/39dd28ee-cdf9-4032-851f-1f20370d1343" />

**Comment by kkaempf** [comment]
Majority of changes for this feature are part of 2.12.0.
In case QA finds something non-working, it needs a separate bug report (to be fixed in 2.12.1).

**Comment by mmartin24** [comment]
Still occuring in `fleet:107.0.0+up0.13.0-beta.4`.
Reviewed with @0xavi0 . He will try to do quick fix

**Comment by mmartin24** [comment]
> > Does the error about no version being found also stay in the HelmOp's status, or is only the UI outdated, with the HelmOp having been updated as a result of polling?
> > The event visibility issue should be fixed by [#3858](https://github.com/rancher/fleet/pull/3858).
> 
> Yes, also found in status. It seems a backend issue:
> 
> When I pull the logs I can see that error as well:
> 
> ```
> k logs -n cattle-fleet-system helmops-5f5d69bc59-7chrq | grep "could not get a chart version" | tail -1
> ```
> 
> output:
> 
> E0708 12:42:13.985102       7 event.go:359] "Server rejected event (will not retry!)" err="events \"test.18504724f5a00e88\" is forbidden: User \"system:serviceaccount:cattle-fleet-system:helmops\" cannot patch resource \"events\" in API group \"\" in the namespace \"fleet-local\"" event="&Event{ObjectMeta:{test.18504724f5a00e88  fleet-local   21832 0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []},InvolvedObject:ObjectReference{Kind:HelmOp,Namespace:fleet-local,Name:test,UID:154b78ea-d26e-447a-8fe3-9e2067875baf,APIVersion:fleet.cattle.io/v1alpha1,ResourceVersion:21974,FieldPath:,},Reason:FailedToGetNewChartVersion,Message:could not get a chart version: no chart name found,Source:EventSource{Component:fleet-helmops,Host:,},FirstTimestamp:2025-07-08 12:41:19 +0000 UTC,LastTimestamp:2025-07-08 12:42:13.983940533 +0000 UTC m=+7059.431223319,Count:12,Type:Warning,EventTime:0001-01-01 00:00:00 +0000 UTC,Series:nil,Action:,Related:nil,ReportingController:fleet-helmops,ReportingInstance:,}"
> <img alt="Image" width="1878" height="931" src="https://private-user-images.githubusercontent.com/37271841/464024062-56bf8284-65b4-45c6-892b-4ea2b1b2d5b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMwODYzNzAsIm5iZiI6MTc1MzA4NjA3MCwicGF0aCI6Ii8zNzI3MTg0MS80NjQwMjQwNjItNTZiZjgyODQtNjViNC00NWM2LTg5MmItNGVhMmIxYjJkNWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzIxVDA4MjExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1MTY5ZTFlYjFmMGU5MWEzM2UyYWIxMjUzOTkyNTIwM2I5Y2ZjNDBjNjNmZWE1NmZjYjRlYWQ1YmYwZDgzZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uzLgwW4b0NTvD4f1bGpfT9Daa2TvGdGbR6h-wzSu53E"> <img alt="Image" width="1898" height="923" src="https://private-user-images.githubusercontent.com/37271841/464024061-39dd28ee-cdf9-4032-851f-1f20370d1343.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMwODYzNzAsIm5iZiI6MTc1MzA4NjA3MCwicGF0aCI6Ii8zNzI3MTg0MS80NjQwMjQwNjEtMzlkZDI4ZWUtY2RmOS00MDMyLTg1MWYtMWYyMDM3MGQxMzQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzIxVDA4MjExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0YjFhNWJhNGJmZmE5OTVkYzgyZTMxYzI2MDUwNzkwN2Q2NWQxMmU2MGZkYjE1ZTNiOTBkNTY0MTYyODMyZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.w2tkEm3AZqhtY0ZEvfXzbd2J-JWPaaAd3FhnWo-_ec4">

Tested along with https://github.com/rancher/fleet/issues/3896#issuecomment-3095692626 on `107.0.0-up0.13.0-rc.3`
It seems indeed to be working ok. Pls see comment and video within.
